Fix build errors
The elfio subdirectory addition is due to a change in bpf_conformance

The execute_progress line change is because a build error has been there since
https://github.com/vbpf/ebpf-verifier/pull/519 where
https://github.com/vbpf/ebpf-verifier/actions/runs/6275811448/job/17044135123
for example shows (starting at line 27 in the log):

Unknown command: 'ARGS'
NuGet.Commands.CommandException: Unknown command: 'ARGS'
   at NuGet.CommandLine.CommandManager.GetCommand(String commandName)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
Feeds used:
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

[execute_process](https://cmake.org/cmake/help/latest/command/execute_process.html)
should not have ARGS whereas
[exec_program](https://cmake.org/cmake/help/latest/command/exec_program.html)
does.

Signed-off-by: Dave Thaler <dthaler1968@gmail.com>